#define MENU "Menu"
#define BEST_OF "Best of"
#define BEST_OF_3_SETS "  3 sets"
#define BEST_OF_5_SETS "  5 sets"
#define WHO_SERVES "Who serves"
#define OPP_SERVES "  Opponent serves"
#define YOU_SERVE "  You serve"
#define START_MATCH "Start match"
#define WHO_SERVES_MARK "*"
#define EMPTY_TEXT ""
#define LOVE_SCORE "love"
#define FIFTEEN_SCORE "fifteen"
#define THIRTY_SCORE "thirty"
#define FORTY_SCORE "forty"
#define AD_SCORE "advantage"
#define TIEBREAK_SCORE "tiebreak"
#define ADVANTAGE_YOU "advantage you"
#define ADVANTAGE_OPP "advantage opp."
#define DEUCE_SCORE "deuce"
#define ALL_SCORE " all"
#define SPACE_SCORE " "
#define STATIC_SCORE_TEXT "Sets  Games Points"
#define MATCHOVER_SCORE "Match over"
#define QUESTION_END_MATCH "End match?"